"""migrations for employee

Revision ID: f6e3c43294c6
Revises: 
Create Date: 2025-12-08 20:19:03.772594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e3c43294c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('emp_firstname', sa.String(length=30), nullable=False),
    sa.Column('emp_midname', sa.String(length=30), nullable=True),
    sa.Column('emp_lastname', sa.String(length=30), nullable=False),
    sa.Column('emp_email', sa.String(length=50), nullable=False),
    sa.Column('emp_age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_index(op.f('ix_employees_emp_email'), 'employees', ['emp_email'], unique=True)
    op.create_index(op.f('ix_employees_emp_id'), 'employees', ['emp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_emp_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_emp_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
